---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: notify-slack-on-failure
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Sends an error message to Slack using postMessage API if managed pipelines fail.
    Optionally, it can also send a notification on success.
  params:
    - name: secretName
      type: string
      description: Name of secret which contains authentication token for app
    - name: secretKeyName
      type: string
      description: Name of key within secret which contains webhook URL
    - name: release
      type: string
      description: Namespaced name of release - should be in format "namespace/name"
    - name: notifySuccess
      type: string
      description: If set to "true", it will also send notification on success
      default: "false"
    - name: slackHandles
      type: string
      description: Comma-separated list of Slack member IDs or group IDs to be tagged on failures
      default: ""
    - name: tagSuccess
      type: string
      description: |-
        If set to "true", will tag users in success notifications as well
        (only applies when notifySuccess is true)
      default: "false"
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the community-catalog tasks to be used are stored
      default: https://github.com/konflux-ci/community-catalog.git
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
  tasks:
    - name: fail-intentionally
      taskSpec:
        steps:
          - name: fail
            image: quay.io/konflux-ci/release-service-utils:latest
            script: |
              #!/bin/sh
              echo "Intentionally failing the pipeline..."
              exit 1
    - name: notify-slack-on-failure
      runAfter:
        - fail-intentionally
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/notify-slack-on-failure/notify-slack-on-failure.yaml
      params:
        - name: secretName
          value: $(params.secretName)
        - name: secretKeyName
          value: $(params.secretKeyName)
        - name: release
          value: $(params.release)
        - name: notifySuccess
          value: $(params.notifySuccess)
        - name: slackHandles
          value: $(params.slackHandles)
        - name: tagSuccess
          value: $(params.tagSuccess)
